/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2025-09-10 08:35:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1755501634378L));
    _jspx_dependants.put("jar:file:/D:/TeamPj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GAGI/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>회원가입</h1>\r\n");
      out.write("\r\n");
      out.write("    <form name=\"JoinForm\" id=\"joinForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/join\" method=\"post\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                	<label for=\"userid\">아이디 (이메일)</label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input type=\"email\" name=\"email\" id=\"userid\" onkeyup=\"validateEmail()\" required>\r\n");
      out.write("                        <input type=\"button\" onclick=\"checkId()\" value=\"중복확인\">\r\n");
      out.write("                        <p id=\"email-rule-msg\" class=\"error-msg\">\r\n");
      out.write("                        	* 이메일을 올바르게 입력하세요\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>    \r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\">\r\n");
      out.write("                    <div id=\"id-area\"></div> <!-- AJAX 결과 표시 -->\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write(" 			<tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                	<label for=\"username\">이름</label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                	<input type=\"text\" name=\"username\" id=\"username\" required>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                	<label for=\"password\">비밀번호</label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                	<input type=\"password\" name=\"password\" id=\"password\" placeholder=\"4~20자로 입력\" onkeyup=\"validatePassword()\" required>\r\n");
      out.write("                	<p id=\"pw-rule-msg\" class=\"error-msg\">\r\n");
      out.write("                		* 영문/숫자/특수문자 2가지 이상 조합(8~20자)<br>	\r\n");
      out.write("                		* 3개 이상 연속되거나 동일한 문자/숫자 제외<br>	\r\n");
      out.write("                		* 아이디(이메일) 제외	\r\n");
      out.write("                	</p>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                	<label for=\"passwordConfirm\">비밀번호 확인</label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                	<input type=\"password\" id=\"passwordConfirm\" placeholder=\"비밀번호 확인\" onkeyup=\"checkPwConfirm()\" required>\r\n");
      out.write("                	<div id=\"pw-msg\"></div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                	<label for=\"nickname\">닉네임</label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                	<div>\r\n");
      out.write("                		<input type=\"text\" name=\"nickname\" id=\"nickname\" onkeyup=\"validateNickname()\" required>\r\n");
      out.write("                		<input type=\"button\" onclick=\"checkNm()\" value=\"중복확인\">\r\n");
      out.write("                		<p id=\"nickname-rule-msg\" class=\"error-msg\">\r\n");
      out.write("                			* 닉네임은 2~10자, 한글/영문/숫자만 사용 가능합니다.\r\n");
      out.write("                		</p>\r\n");
      out.write("                	</div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\">\r\n");
      out.write("                    <div id=\"id-area-nickname\"></div> <!-- AJAX 결과 표시 -->\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\">\r\n");
      out.write("                	<label for=\"phone\">전화번호</label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                	<input type=\"text\" name=\"phone\" id=\"phone\" placeholder=\"010-1234-5678\" onkeyup=\"validatePhone()\" required>\r\n");
      out.write("                	<p id=\"phone-rule-msg\" class=\"error-msg\">\r\n");
      out.write("                		* 전화번호 형식: 010-1234-5678\r\n");
      out.write("                	</p>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>          \r\n");
      out.write("        </table>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 체크박스 영역 -->\r\n");
      out.write("    	<div class=\"checklist\">\r\n");
      out.write("        	<label><input type=\"checkbox\" required> 휴대폰 인증확인</label><br>\r\n");
      out.write("        	<label><input type=\"checkbox\" required> [필수] 만 14세 이상입니다</label><br>\r\n");
      out.write("        	<label><input type=\"checkbox\" required> [필수] 개인정보 이용</label><br>\r\n");
      out.write("        	<label><input type=\"checkbox\" required> [필수] 고유식별정보 처리</label>\r\n");
      out.write("    	</div>\r\n");
      out.write("        \r\n");
      out.write("        <div>\r\n");
      out.write("            <input type=\"submit\" value=\"회원가입\">\r\n");
      out.write("            <input type=\"reset\" value=\"다시입력\">\r\n");
      out.write("            <input type=\"button\" value=\"홈으로\" onclick=\"location.href='/'\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/join.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
